### PR TITLE
Added index toggle menu

### PR DESCRIPTION
**Pull request by mpopp75**
Added a toggle button with an index menu, see http://media.mpopp.net/html5test.png

Commit f82d2d4 is just to get rid of white spaces at the end of lines, because my editor is set to remove them, so it allows for a clean commit 44ac3d4 including only the actual changes.

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
Hi Markus, thanks for this pull request.

I've been thinking about this for a while and I definitely do like the functionality of having an index menu. But I'm not sure how to properly integrate this into the design of the site. 

First of all, I do not think I want a button with the name 'Index' in the top right corner. I'm thinking more about a 'hamburger' in the top left corner.

I also think we can make the index itself visually a bit more attractive. First I was thinking about using a popover in the same style as the rest of the site (white background, thick border pointing towards the origin of the menu). But using a proper sidebar with transition effect would also look great.

Take a look at this demo: http://tympanus.net/Development/SidebarTransitions/
I'm thinking the 'Rotate pusher' or 'Push' transition would fit nicely.

Below is a mockup of what I am thinking about. Is this something you could do? Or should I look at it based on your code?

Cheers,
Niels

mockup

**Comment by mpopp75** [comment]
Hi Niels, thanks for your feedback!

Let me give this a try. I assume this doesn't block the 5.0 release and can be added later on?!

Initially I had the menu on the left, but on small screen sizes the elements collided with other elements on the page. First I moved them to the right for the small screen sizes which are affected, later I moved them generally to the right for consistency. I agree, on the left it's better, that's where most people are more likely to expect the menu.

Cheers,
Markus

**Comment by NielsLeenheer** [comment]
Right, this isn't a blocker for the release. The test suite is pretty much final and all UI refinements can be worked on independently.

**Comment by mpopp75** [comment]
Here is the updated version, according to your mockup. Went fairly smoothly.

Here is a screenshot of what it looks like now: http://media.mpopp.net/html5test-2.png

I added a content wrapper div around the "old content", so I could style it separately, and moved the index div below the content wrapper div. I also added IDs to the main categories (Semantics, Device Access etc.), now the links go really to the categories rather than the first item within the category, as did my previous version.

Of course this will require more testing, especially on mobile and not so common desktop browsers. But I think this should be a pretty good starting point :).

**Comment by NielsLeenheer** [comment]
Great!

I've merged it locally and made some small tweaks to the animations. They are now based on transforms instead of position, so they are a bit more smoother. I've also replaced the hamburger image with an icon from the icon font.

http://alpha.html5test.com/index.html

There are still some other things I want to look at before landing these landing these changes. Some of the changes are breaking other pages. I'll have that sorted out later today.

**Comment by NielsLeenheer** [comment]
Merged!

**Pull request merged**
