### PR TITLE
Remove forminput, formchange, dispatchFormInput and dispatchFormChange checks.

### PR DESCRIPTION
**Pull request by mounirlamouri**
Remove forminput, formchange, dispatchFormInput and dispatchFormChange checks, following the recent specification change.
See: http://www.w3.org/Bugs/Public/show_bug.cgi?id=11129&mark=21-22#c21
and: http://html5.org/tools/web-apps-tracker?from=5927&to=5928

### CODE REVIEW

**Comment by NielsLeenheer** [comment]
Will be removed from the test when the W3C published the next snapshot of the HTML5 spec.

**Comment by mounirlamouri** [comment]
Why do you rely on W3C snapshots? Usually, WHATWG HTML specs are considered as the reference.

**Comment by mounirlamouri** [comment]
I believe it has been updated: http://www.w3.org/TR/2011/WD-html5-20110405/

**Comment by NielsLeenheer** [comment]
Removed on beta.html5test.com

**Pull request closed without merging**
